export const plans = [
    {
      name: "Free",
      price: "$0",
      priceId: "",
      period: "month",
      desc: "For personal note-taking & light AI usage",
      features: [
        "Unlimited notes",
        "Note basics: text, image, edit, voice, icon",
        "Favourite notes + note calendar",
        "100MB storage for image + voice",
        "50 AI credits / month",
        "Low daily AI cap",
        "Basic AI: ask AI + summary",
      ],
      highlight: false,
      badge: null,
      button: "Current Plan",
    },
    {
      name: "Starter",
      price: "$10",
      priceId: "pri_01kqgsntf1v3qvgv0h9mtnyp90",
      period: "month",
      desc: "For regular users who want more AI",
      features: [
        "Unlimited notes",
        "Note basics: text, image, edit, voice, icon",
        "Favourite notes + note calendar",
        "500MB storage for image + voice",
        "250 AI credits / month",
        "Medium daily AI cap",
        "Ask AI + summary + read note aloud",
        "Faster processing than Free",
      ],
      highlight: true,
      badge: "Most Popular",
      button: "Upgrade to Starter",
    },
    {
      name: "Pro",
      price: "$20",
      priceId: "pri_01kqkcrf3jmx4y5f4e1n2pa96k",
      period: "month",
      desc: "For heavy AI usage and power users",
      features: [
        "Unlimited notes",
        "Note basics: text, image, edit, voice, icon",
        "Favourite notes + note calendar",
        "5GB storage for image + voice",
        "1000 AI credits / month",
        "High daily AI cap",
        "Ask AI + summary + read note aloud",
        "Speech mode with Whisper",
        "Mindmap generation from notes",
        "Bulk AI actions + priority processing",
      ],
      highlight: false,
      badge: null,
      button: "Upgrade to Pro",
    },
  ];